name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop      
  
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Put Code at Ubuntu 
        uses: actions/checkout@v3
     
      - name: Configure Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.15

      - run: go test 
      - run: go run math.go
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: adilson1979/go_image:1.0
